/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'brand-green':      '#00d4a4',
        'brand-green-deep': '#00b48a',
        'brand-green-soft': '#7cebcb',
        'brand-tag':        '#3772cf',
        'brand-warn':       '#c37d0d',
        'brand-error':      '#d45656',
        'hero-dark-from':   '#1a3d4a',
        'hero-dark-to':     '#2d5a4f',
        'hero-sky-from':    '#87a8c8',
        'hero-sky-to':      '#f5e9d8',
        canvas:             '#ffffff',
        'canvas-dark':      '#0a0a0a',
        surface:            '#f7f7f7',
        'surface-soft':     '#fafafa',
        'surface-code':     '#1c1c1e',
        hairline:           '#e5e5e5',
        'hairline-soft':    '#ededed',
        'hairline-dark':    '#1f1f1f',
        ink:                '#0a0a0a',
        charcoal:           '#1c1c1e',
        slate:              '#3a3a3c',
        steel:              '#5a5a5c',
        stone:              '#888888',
        muted:              '#a8a8aa',
        'on-dark':          '#ffffff',
        'on-dark-muted':    '#b3b3b3',
      },
      fontFamily: {
        sans: ['InterVariable', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['"Geist Mono"', '"SF Mono"', 'Menlo', 'Consolas', 'monospace'],
      },
      borderRadius: {
        xs:   '4px',
        sm:   '6px',
        md:   '8px',
        lg:   '12px',
        xl:   '16px',
        xxl:  '24px',
        full: '9999px',
      },
      spacing: {
        xxs:          '4px',
        xs:           '8px',
        sm:           '12px',
        md:           '16px',
        lg:           '20px',
        xl:           '24px',
        xxl:          '32px',
        xxxl:         '40px',
        'section-sm': '48px',
        section:      '64px',
        'section-lg': '96px',
        hero:         '120px',
      },
      boxShadow: {
        subtle:         'rgba(0,0,0,0.04) 0px 1px 2px 0px',
        card:           'rgba(0,0,0,0.08) 0px 4px 12px 0px',
        mockup:         'rgba(0,0,0,0.12) 0px 24px 48px -8px',
        'brand-tinted': 'rgba(0,212,164,0.08) 0px 8px 24px',
      },
    },
  },
  plugins: [],
}

